# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

integrand_collection <- function(rt, r2, k0, psi, epsilon, thickness) {
    .Call('planar_integrand_collection', PACKAGE = 'planar', rt, r2, k0, psi, epsilon, thickness)
}

cpp_field_collection <- function(r2, k0, psi, omega, epsilon, thickness, maxEval, reqAbsError, tol, progress) {
    .Call('planar_cpp_field_collection', PACKAGE = 'planar', r2, k0, psi, omega, epsilon, thickness, maxEval, reqAbsError, tol, progress)
}

cpp_layer_fresnel <- function(k0, kx, epsilon, thickness) {
    .Call('planar_cpp_layer_fresnel', PACKAGE = 'planar', k0, kx, epsilon, thickness)
}

cpp_recursive_fresnel <- function(k0, kx, epsilon, thickness, polarisation) {
    .Call('planar_cpp_recursive_fresnel', PACKAGE = 'planar', k0, kx, epsilon, thickness, polarisation)
}

integrand_gb_ml <- function(rt, r2, k0, psi, alpha, w0, epsilon, thickness) {
    .Call('planar_integrand_gb_ml', PACKAGE = 'planar', rt, r2, k0, psi, alpha, w0, epsilon, thickness)
}

integrand_gb_layer <- function(rt, r2, ki, psi, alpha, w0, ni, no, nl, d) {
    .Call('planar_integrand_gb_layer', PACKAGE = 'planar', rt, r2, ki, psi, alpha, w0, ni, no, nl, d)
}

cpp_field_gb_layer <- function(r2, k0, psi, alpha, w0, epsilon, thickness, maxEval, reqAbsError, tol, progress) {
    .Call('planar_cpp_field_gb_layer', PACKAGE = 'planar', r2, k0, psi, alpha, w0, epsilon, thickness, maxEval, reqAbsError, tol, progress)
}

cpp_field_gb_ml <- function(r2, k0, psi, alpha, w0, epsilon, thickness, maxEval, reqAbsError, tol, progress) {
    .Call('planar_cpp_field_gb_ml', PACKAGE = 'planar', r2, k0, psi, alpha, w0, epsilon, thickness, maxEval, reqAbsError, tol, progress)
}

#' @title Transfer matrix formalism for multilayer stacks
#' @description Full calculation for multiple wavelengths
#' @param k0 vector of wavenumbers
#' @param kx complex matrix of incident k parallel
#' @param epsilon complex matrix of epsilon
#' @param thickness vector of thicknesses
#' @param z vector of positions
#' @param psi scalar polarisation angle
#' @param intensity boolean: also return intensities
#' @return list with rs, rp, ts, tp, I (optional)
#' @describeIn multilayer full multi
#' @family multilayer
cpp_multilayer <- function(k0, kx, epsilon, thickness, z, psi, intensity) {
    .Call('planar_cpp_multilayer', PACKAGE = 'planar', k0, kx, epsilon, thickness, z, psi, intensity)
}

#' @title Transfer matrix formalism for multilayer stacks
#' @description Field calculation for one wavelength
#' @param k0 vector of wavenumbers
#' @param kx complex matrix of incident k parallel
#' @param epsilon complex matrix of epsilon
#' @param thickness vector of thicknesses
#' @param z vector of positions
#' @param psi scalar polarisation angle
#' @return list with rs, rp, ts, tp, I
#' @describeIn multilayer full multi
#' @family multilayer
cpp_multilayer_field <- function(k0, kx, epsilon, thickness, z, psi) {
    .Call('planar_cpp_multilayer_field', PACKAGE = 'planar', k0, kx, epsilon, thickness, z, psi)
}

